#!/bin/bash
FLOCK='/usr/bin/flock'
LOCKFILE="/home/chris/$(basename "$0").lock"
CMD_CRON="/home/chris/src/Manchester_SoundPicture/cron/rsync_soslasso.sh"

${FLOCK} \
  -nx "${LOCKFILE}" \
  -c "${CMD_CRON}"
